#!/bin/bash
# Regenerates unitcommonwords.pas - the secret-word pool, compiled into the
# binary so nothing has to be distributed beside it.
#
# A word qualifies if it appears in BOTH:
#   - unitwordlist.pas (a legal guess - generated from the system dictionary
#     by generate_wordlist_unit.sh), and
#   - the frequency list (a word people actually use - see freqlist/README.md).
#
# The output keeps the frequency list's order, most common first, so the
# picker can treat "the first N of a length" as "the N most common".
#
# Usage: ./generate_commonwords_unit.sh [frequency-list]
#   TOP_N=10000 ./generate_commonwords_unit.sh   # only the 10,000 most
#                                                # common words qualify
# Another language is just another list in the same {word} {count} format.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$SCRIPT_DIR/.."
FREQ_FILE="${1:-$SCRIPT_DIR/freqlist/en_50k.txt}"
TOP_N="${TOP_N:-0}"   # 0 = use the whole list
OUTPUT_FILE="$ROOT/unitcommonwords.pas"

if [ ! -f "$FREQ_FILE" ]; then
    echo "Error: frequency list not found: $FREQ_FILE"
    exit 1
fi

DICT=$(mktemp)
trap 'rm -f "$DICT"' EXIT
grep -oE "'[A-Z]+'" "$ROOT/unitwordlist.pas" | tr -d "'" | sort -u > "$DICT"

echo "Guess dictionary: $(wc -l < "$DICT") words"
echo "Frequency list:   $FREQ_FILE"

WORDS=$(awk -v topn="$TOP_N" '
    NR == FNR { dict[$1] = 1; next }
    topn > 0 && FNR > topn { exit }
    {
        w = toupper($1)
        if (w ~ /^[A-Z]+$/ && length(w) >= 3 && length(w) <= 9 &&
            (w in dict) && !(w in seen)) {
            seen[w] = 1
            print w
        }
    }' "$DICT" "$FREQ_FILE")

WORD_COUNT=$(echo "$WORDS" | wc -l)
echo "Common words:     $WORD_COUNT"

cat > "$OUTPUT_FILE" << 'EOF'
unit unitcommonwords;

{ The secret-word pool: every entry is both a legal guess (it is in
  unitwordlist's WORD_LIST) and a word people actually use (it is in the
  frequency list). Ordered most common first, so index doubles as rank.

  Generated by tools/generate_commonwords_unit.sh - do not edit by hand. }

{$mode objfpc}{$H+}

interface

const
  COMMON_WORDS: array[0..WORD_COUNT_PLACEHOLDER] of string = (
EOF

FIRST=true
while IFS= read -r word; do
    if [ "$FIRST" = true ]; then
        echo "    '$word'" >> "$OUTPUT_FILE"
        FIRST=false
    else
        echo "   ,'$word'" >> "$OUTPUT_FILE"
    fi
done <<< "$WORDS"

cat >> "$OUTPUT_FILE" << 'EOF'
  );

implementation

end.
EOF

sed -i "s/WORD_COUNT_PLACEHOLDER/$((WORD_COUNT - 1))/" "$OUTPUT_FILE"

echo "Generated $OUTPUT_FILE"
