#!/bin/bash
# Regenerates www/words.js for the web version of the game, from the
# COMMITTED Pascal units - not from the raw sources - so the web game and
# the desktop game can never disagree about what is a word.
#
#   WZ_WORDS   every legal guess        (unitwordlist.pas)
#   WZ_COMMON  secret pool, ranked      (unitcommonwords.pas)
#   WZ_POTTY   sets off the toilet show (POOP_WORDS in unitfrmmain.pas)
#   WZ_HOUSE   house words              (EXTRA_WORDS in unitwordpicker.pas)

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$SCRIPT_DIR/.."
OUT="$ROOT/www/words.js"

words()  { grep -oE "'[A-Z]+'" | tr -d "'" | tr '\n' ' ' | sed 's/ $//'; }
block()  { sed -n "/$2: array/,/);/p" "$1"; }

mkdir -p "$ROOT/www"
{
  echo "// Generated by tools/generate_words_js.sh - do not edit by hand."
  printf 'const WZ_WORDS="%s".split(" ");\n' \
    "$(words < "$ROOT/unitwordlist.pas")"
  printf 'const WZ_COMMON="%s".split(" ");\n' \
    "$(words < "$ROOT/unitcommonwords.pas")"
  printf 'const WZ_POTTY="%s".split(" ");\n' \
    "$(block "$ROOT/unitfrmmain.pas" POOP_WORDS | words)"
  printf 'const WZ_HOUSE="%s".split(" ");\n' \
    "$(block "$ROOT/unitwordpicker.pas" EXTRA_WORDS | words)"
} > "$OUT"

echo "Generated $OUT ($(wc -c < "$OUT") bytes)"
